CREATE TABLE PEDIDOS
(
id_pedido INT PRIMARY KEY,
id_usuario INT NOT NULL,
fecha_pedido DATETIME DEFAULT CURRENT_TIMESTAMP,
total DECIMAL(10, 2) NOT NULL,
FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
);